import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    "brand.name": "Luxury Finishing",
    "brand.location": "Cairo, Egypt",

    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.cta": "Free Consultation",
    "nav.quote": "Get a Quote",
    "nav.legal": "Legal Center",
    "nav.channels": "Official Channels",
    "nav.sitemap": "Sitemap",

    "hero.badge": "Specialists in luxury residential finishing since 2010",
    "hero.slide1.title": "From Foundation to Final Delivery",
    "hero.slide1.subtitle": "Your Dream Home Starts Here",
    "hero.slide2.title": "Interior Designs That Come Alive",
    "hero.slide2.subtitle": "We Turn Your Vision Into Reality",
    "hero.slide3.title": "European Materials, Global Standards",
    "hero.slide3.subtitle": "Quality Without Compromise",
    "hero.slide4.title": "Over 120 Residential Units Completed",
    "hero.slide4.subtitle": "15+ Years of Luxury Finishing Experience",
    "hero.desc": "We design and execute your residential unit finishing with modern designs and European quality — from the first consultation to turnkey delivery.",
    "hero.cta.quote": "Get a Free Quote",
    "hero.cta.work": "View Our Work",

    "stat.years": "Years Experience",
    "stat.units": "Residential Units",
    "stat.designs": "Exclusive Designs",
    "stat.satisfaction": "Client Satisfaction",

    "services.badge": "Our Services",
    "services.title": "Integrated Finishing Services",
    "services.desc": "We offer a complete range of luxury residential finishing services with the finest materials and expert craftsmanship.",
    "service.structural": "Structural Modifications",
    "service.structural.desc": "Demolition and reconstruction, hidden electrical wiring, advanced plumbing, central AC installation.",
    "service.finishing": "Architectural Finishing",
    "service.finishing.desc": "Plastering, decorative paints, wallpaper. Premium flooring: parquet, marble, and porcelain.",
    "service.gypsum": "Gypsum & Decor",
    "service.gypsum.desc": "Decorative gypsum board, suspended ceilings, modern lighting distribution, hidden LED lighting.",
    "service.carpentry": "Carpentry & Kitchens",
    "service.carpentry.desc": "Custom kitchen manufacturing, wardrobes, TV units, decorative panels — all made to measure.",
    "service.handover": "Final Handover",
    "service.handover.desc": "Deep cleaning, final inspection, testing all systems, and handing over the keys to you.",

    "showcase.badge": "Featured Work",
    "showcase.title": "Luxury Residential Finishing Showcases",
    "showcase.desc": "Browse our premium finished residential projects — each reflecting our commitment to quality and elegance.",
    "showcase.living": "Luxury Living Rooms",
    "showcase.livingDesc": "Modern designs with decorated ceilings and hidden lighting",
    "showcase.bedroom": "Elegant Bedrooms",
    "showcase.bedroomDesc": "Premium materials and distinctive decorative touches",
    "showcase.kitchen": "Modern Kitchens",
    "showcase.kitchenDesc": "Manufacturing and installing kitchens with the finest materials",
    "showcase.bathroom": "Hotel-Style Bathrooms",
    "showcase.bathroomDesc": "Natural marble and European sanitary fixtures",
    "showcase.sectionBadge": "What We Master",
    "showcase.sectionTitle": "Residential Finishing with Hotel Standards",
    "showcase.sectionDesc": "Every corner of your home deserves special attention — from the living room to the finest bathroom details",

    "expertise.badge": "Why Choose Us",
    "expertise.title": "Expert Craftsmanship & Precision",
    "expertise.desc": "15+ years of experience transforming residential spaces into masterpieces of luxury finishing.",
    "expertise.whyTitle": "Why Do Our Clients Trust Us with Their Homes?",
    "expertise.whyDesc": "We don't do ordinary finishing — we create a space that reflects your personality and refined taste with the highest professionalism.",
    "expertise.card1": "Comprehensive Quality Guarantee",
    "expertise.card1Desc": "We commit to the highest quality standards with warranty on all executed work.",
    "expertise.card2": "Modern & Innovative Designs",
    "expertise.card2Desc": "3D designs before execution help you visualize your home before starting.",
    "expertise.card3": "Strict Deadline Commitment",
    "expertise.card3Desc": "Clear timelines with regular updates until delivery.",
    "expertise.card4": "Premium European Materials",
    "expertise.card4Desc": "We work with the best material suppliers to ensure durability and beauty.",

    "projects.badge": "Our Projects",
    "projects.title": "A Portfolio of Excellence",
    "projects.desc": "Explore our diverse collection of luxury finished residential units.",
    "projects.viewAll": "View All Projects",

    "timeline.badge": "Our Journey",
    "timeline.title": "From Concept to Completion",
    "timeline.desc": "Our streamlined process ensures a flawless finishing experience.",
    "timeline.mainTitle": "From Idea to Handover in 5 Steps",
    "timeline.step": "Step",
    "timeline.s1": "Consultation & Site Visit",
    "timeline.s1Desc": "Our team visits the apartment, takes precise measurements, and discusses your ideas.",
    "timeline.s2": "Initial Design (3D)",
    "timeline.s2Desc": "We provide a 3D design of the spaces before starting work.",
    "timeline.s3": "Approving Quotes & Materials",
    "timeline.s3Desc": "We finalize materials and costs with complete transparency.",
    "timeline.s4": "Execution & Supervision",
    "timeline.s4Desc": "We start work under the supervision of specialized engineers.",
    "timeline.s5": "Final Handover",
    "timeline.s5Desc": "We hand you your dream home ready to move in.",

    "testimonials.badge": "Client Reviews",
    "testimonials.title": "What Our Clients Say",
    "testimonials.desc": "Real feedback from homeowners who trusted us with their dream homes.",
    "testimonials.sectionTitle": "What Our Clients Say",
    "testimonials.t1.name": "Ahmed Mohamed",
    "testimonials.t1.location": "Apartment - Fifth Settlement",
    "testimonials.t1.text": "A professional and precise team, they adhered to the timeline and the quality was more than excellent. I highly recommend them.",
    "testimonials.t2.name": "Sara Abdullah",
    "testimonials.t2.location": "Villa - Sheikh Zayed",
    "testimonials.t2.text": "One of the best finishing companies I've worked with. The attention to detail and interior design was amazing.",
    "testimonials.t3.name": "Mohamed Hassan",
    "testimonials.t3.location": "Duplex - Al Rehab",
    "testimonials.t3.text": "An excellent experience from start to finish. The engineers were very cooperative and the final result exceeded our expectations.",

    "cta.title": "Ready to Transform Your Home?",
    "cta.desc": "Get a free consultation and detailed quote for your residential finishing project.",
    "cta.button": "Get Free Quote",
    "cta.call": "Call Us Now",

    "footer.about": "Specialists in finishing and designing luxury residential units with modern designs and European quality.",
    "footer.quickLinks": "Quick Links",
    "footer.services": "Services",
    "footer.contact": "Contact Us",
    "footer.rights": "All rights reserved",
    "footer.privacy": "Privacy Policy",
    "footer.faq": "FAQ",
    "footer.location": "Cairo, Egypt",
    "footer.legal": "Legal Center",
    "footer.channels": "Official Channels",
    "footer.sitemap": "Sitemap",

    "about.heroTitle": "About Us",
    "about.title": "About Luxury Finishing",
    "about.desc": "We started our journey in luxury finishing since 2010, carrying the motto of quality and refined taste.",
    "about.story": "Our Story",
    "about.storyText": "We evolved from mere contractors to partners for homeowners in achieving their dream. We believe every home deserves an artistic touch reflecting its owners' personality.",
    "about.vision": "Vision",
    "about.visionText": "To be the first choice for luxury residential finishing in the region.",
    "about.mission": "Mission",
    "about.missionText": "Delivering an integrated experience combining innovative design and masterful execution.",
    "about.values": "Our Values",
    "about.quality": "Quality",
    "about.commitment": "Commitment",
    "about.innovation": "Innovation",
    "about.transparency": "Transparency",
    "about.yearsExp": "Years Experience",
    "about.projectsDone": "Projects Completed",
    "about.repeatClients": "Repeat Clients",
    "about.team": "Leadership Team",
    "about.ceo": "CEO",
    "about.projectMgr": "Project Manager",
    "about.designMgr": "Design Manager",

    "blog.heroTitle": "Blog",
    "blog.title": "Our Blog",
    "blog.desc": "Latest trends in décor and finishing.",
    "blog.readMore": "Read More",
    "blog.post1": "Smart Ideas for Open Living Room Design",
    "blog.post2": "Your Guide to Choosing Flooring: Parquet, Marble, or Porcelain?",
    "blog.post3": "Latest Decorative Paint Color Trends for 2024",
    "blog.post4": "How to Choose the Perfect Kitchen Design for Your Home",
    "blog.post5": "Secrets of Professional Interior Lighting",
    "blog.post6": "Guide to Choosing the Right Bathroom Materials",
    "blog.cat.interior": "Interior Design",
    "blog.cat.materials": "Building Materials",
    "blog.cat.decor": "Décor",
    "blog.excerpt1": "Discover the best ways to design open living rooms that combine elegance and functionality.",
    "blog.excerpt2": "A comprehensive comparison of flooring types to help you make the best decision for your home.",
    "blog.excerpt3": "Learn about the latest color trends that add a modern touch to your spaces.",
    "blog.excerpt4": "Practical tips for designing a kitchen that combines beauty and practicality.",
    "blog.excerpt5": "How to use lighting to transform any space into a masterpiece.",
    "blog.excerpt6": "Everything you need to know about luxury bathroom materials.",
    "blogSection.title": "Latest Décor & Finishing Trends",

    "contact.heroTitle": "Contact Us",
    "contact.title": "Contact Us",
    "contact.desc": "We're happy to hear from you for any inquiry or request.",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.address": "Address",
    "contact.addressValue": "Commercial District - Cairo",
    "contact.sendMessage": "Send Us a Message",
    "contact.fullName": "Full Name",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Phone Number",
    "contact.propertyType": "Property Type",
    "contact.selectProperty": "Select Property Type",
    "contact.apartment": "Apartment",
    "contact.villa": "Villa",
    "contact.duplex": "Duplex",
    "contact.other": "Other",
    "contact.area": "Property Area (m²)",
    "contact.message": "Your Message",
    "contact.submit": "Send Message",
    "contact.success": "Your message was sent successfully!",
    "contact.successDesc": "We'll get back to you as soon as possible.",
    "contact.workingHours": "Working Hours",
    "contact.satThu": "Saturday - Thursday",
    "contact.friday": "Friday",
    "contact.closed": "Closed",
    "contact.ourLocation": "Our Location",

    "projectsPage.heroTitle": "Our Portfolio",
    "projectsPage.heroDesc": "Browse our comprehensive collection of residential and commercial finishing projects with the highest quality and professionalism.",
    "projectsPage.project": "project",
    "projectsPage.photo": "photo",
    "projectsPage.categories": "categories",
    "projectsPage.all": "All",
    "projectsPage.showProjects": "Projects View",
    "projectsPage.showGallery": "Gallery View",
    "projectsPage.backToProjects": "Back to Projects",
    "projectsPage.photos": "photos",
    "projectsPage.showMore": "Show More",
    "projectsPage.remaining": "remaining photos",
    "projectsPage.showing": "Showing",
    "projectsPage.of": "of",
    "projectsPage.view": "View",

    "servicesPage.heroTitle": "Our Services",
    "servicesPage.heroDesc": "We offer a complete range of finishing and interior design services with the highest quality standards.",
    "servicesPage.extraTitle": "Additional Services",
    "servicesPage.s1.title": "Structural Modifications & Installations",
    "servicesPage.s1.desc": "Demolition and reconstruction, hidden electrical wiring, advanced plumbing, central AC installation and distributed cooling.",
    "servicesPage.s2.title": "Luxury Architectural Finishing",
    "servicesPage.s2.desc": "All finishing works at the highest quality: plastering, decorative paints, wallpaper. Premium flooring: parquet, marble, and porcelain.",
    "servicesPage.s3.title": "Gypsum Board & Décor",
    "servicesPage.s3.desc": "Multi-level suspended gypsum board ceilings, cornices, decorative walls, hidden LED lighting for a luxurious atmosphere.",
    "servicesPage.s4.title": "Carpentry & Kitchens",
    "servicesPage.s4.desc": "Custom design, manufacturing and installation of bedrooms, kitchens, storage units and smart solutions.",
    "servicesPage.s5.title": "Final Finishing & Handover",
    "servicesPage.s5.desc": "Installation of luxury sanitary and electrical fixtures, full kitchen setup, glass and mirrors, turnkey delivery.",
    "servicesPage.extra1.title": "Engineering Consultations",
    "servicesPage.extra1.desc": "We provide specialized engineering consultations to help you make the right decisions.",
    "servicesPage.extra2.title": "Project Supervision",
    "servicesPage.extra2.desc": "Comprehensive engineering supervision to ensure the highest quality standards.",
    "servicesPage.extra3.title": "After-Sales Services",
    "servicesPage.extra3.desc": "Periodic maintenance and post-delivery services for your complete comfort.",

    "faq.heroTitle": "Frequently Asked Questions",
    "faq.q1": "How long does a finishing project take?",
    "faq.a1": "Duration depends on project size and type. On average, 3-6 months for apartments and 6-12 months for villas.",
    "faq.q2": "Do you offer a warranty?",
    "faq.a2": "Yes, we offer a comprehensive 1-year warranty on all finishing work and 2 years on structural work.",
    "faq.q3": "How is the cost determined?",
    "faq.a3": "Cost is based on property area, finishing type, and chosen materials. We provide a detailed, transparent quote before starting.",
    "faq.q4": "Can I choose my own materials?",
    "faq.a4": "Absolutely! We help you choose the best materials and provide multiple options to suit your budget and taste.",
    "faq.q5": "Do you provide 3D designs before execution?",
    "faq.a5": "Yes, we provide 3D designs for all spaces so you can visualize the final result before starting.",
    "faq.q6": "What payment methods are available?",
    "faq.a6": "We offer flexible payment plans. Payments are made in stages linked to work progress.",
    "faq.q7": "Do you offer post-delivery maintenance?",
    "faq.a7": "Yes, we offer periodic and emergency maintenance after delivery for your complete comfort.",
    "faq.q8": "Can I track the work progress?",
    "faq.a8": "Absolutely! We provide regular updates with photos and videos, and you can visit the site anytime.",

    "projectsSection.badge": "Portfolio",
    "projectsSection.title": "Our Latest Completed Projects",
    "projectsSection.desc": "Discover a selection of residential and commercial finishing projects we're proud to have executed",
    "projectsSection.viewAll": "View All",

    "quote.badge": "Free Quote",
    "quote.title": "Get a Quote for Your Project",
    "quote.desc": "Complete the form below and our team will contact you with a detailed quote within 24 hours",
    "quote.step1": "Basic Info",
    "quote.step2": "Property Details",
    "quote.step3": "Required Services",
    "quote.step4": "Budget",
    "quote.step5": "Review",
    "quote.name": "Full Name",
    "quote.phone": "Phone Number",
    "quote.email": "Email (optional)",
    "quote.propertyType": "Property Type",
    "quote.area": "Area (m²)",
    "quote.floors": "Number of Floors",
    "quote.location": "Location",
    "quote.budget": "Estimated Budget",
    "quote.notes": "Additional Notes",
    "quote.next": "Next",
    "quote.prev": "Previous",
    "quote.submit": "Submit Request",
    "quote.success.title": "Request Submitted Successfully!",
    "quote.success.desc": "Our team will contact you within 24 hours with a detailed quote.",
    "quote.newRequest": "Submit New Request",
    "quote.selectServices": "Select the services you need (you can select more than one)",
    "quote.approxBudget": "Approximate Budget",
    "quote.basicInfo": "Your Basic Info",
    "quote.propertyDetails": "Property Details",
    "quote.selectedServices": "Selected Services",
    "quote.notesLabel": "Notes",
    "quote.nameLabel": "Name",
    "quote.phoneLabel": "Phone",
    "quote.emailShort": "Email",
    "quote.type": "Type",
    "quote.areaLabel": "Area",
    "quote.locationLabel": "Location",
    "quote.floorsLabel": "Floors",
    "quote.budgetLabel": "Budget",
    "quote.error": "An error occurred",
    "quote.errorDesc": "Could not submit the request. Please try again.",
    "quote.enterName": "Enter your full name",
    "quote.enterPhone": "01xxxxxxxxx",
    "quote.enterEmail": "example@email.com",
    "quote.enterArea": "e.g. 150",
    "quote.enterFloors": "e.g. 2",
    "quote.enterLocation": "e.g. Fifth Settlement, New Cairo",
    "quote.enterNotes": "Any additional details you'd like to share...",
    "quote.service.structural": "Structural Modifications",
    "quote.service.finishing": "Architectural Finishing",
    "quote.service.gypsum": "Gypsum & Decor",
    "quote.service.carpentry": "Carpentry & Kitchens",
    "quote.service.handover": "Final Handover",
    "quote.service.consulting": "Engineering Consultations",
    "quote.budget1": "Less than 100,000 EGP",
    "quote.budget2": "100,000 - 300,000 EGP",
    "quote.budget3": "300,000 - 500,000 EGP",
    "quote.budget4": "500,000 - 1,000,000 EGP",
    "quote.budget5": "More than 1,000,000 EGP",

    "chat.title": "Luxury Finishing Assistant",
    "chat.subtitle": "Maintenance, inquiries, attachments, and voice support",
    "chat.placeholder": "Type your message...",
    "chat.welcome": "Welcome to Luxury Finishing. I can help with general inquiries, create architectural maintenance requests, or check an existing request.",
    "chat.newConversation": "New conversation",
    "chat.history": "Previous conversations",
    "chat.download": "Download transcript",
    "chat.close": "Close chat",
    "chat.open": "Open chat",
    "chat.historyTitle": "Conversation history",
    "chat.historyLead": "You can restore, remove, or clear saved conversations.",
    "chat.historyEmpty": "No saved conversations yet",
    "chat.historyEmptyLead": "History is saved automatically after the first user message.",
    "chat.historyCount": "saved conversations",
    "chat.current": "Current",
    "chat.clearAll": "Clear all",
    "chat.saved": "saved",
    "chat.removeAttachment": "Remove attachment",
    "chat.attach": "Attach files",
    "chat.record": "Voice recording",
    "chat.stopRecord": "Stop recording",
    "chat.listen": "Listen",
    "chat.send": "Send",
    "chat.attachPlaceholder": "Type your message or attach files...",
    "chat.downloadSuccess": "The current conversation transcript was downloaded.",
    "chat.clearSuccess": "Saved conversation history was cleared.",
    "chat.downloadEmpty": "There is no conversation to download right now.",
    "chat.supportLead": "Text and voice chat, maintenance requests, attachments, and previous conversations.",
    "chat.attachmentsAssist": "Integrated assistant for maintenance, inquiries, and attachments",
    "chat.latestUpdate": "Last updated",

    "theme.light": "Light",
    "theme.dark": "Dark",

    "property.apartment": "Apartment",
    "property.villa": "Villa",
    "property.duplex": "Duplex",
    "property.penthouse": "Penthouse",
    "property.townhouse": "Townhouse",
    "property.studio": "Studio",
  },
  ar: {
    "brand.name": "لاكشري فينيشينج",
    "brand.location": "القاهرة، مصر",

    "nav.home": "الرئيسية",
    "nav.about": "عن الشركة",
    "nav.services": "خدماتنا",
    "nav.projects": "مشاريعنا",
    "nav.blog": "المدونة",
    "nav.contact": "اتصل بنا",
    "nav.cta": "استشارة مجانية",
    "nav.quote": "طلب عرض سعر",
    "nav.legal": "المركز القانوني",
    "nav.channels": "القنوات الرسمية",
    "nav.sitemap": "خريطة الموقع",

    "hero.badge": "متخصصون في التشطيبات السكنية الفاخرة منذ 2010",
    "hero.slide1.title": "من التأسيس إلى التسليم النهائي",
    "hero.slide1.subtitle": "بيت العمر يبدأ من هنا",
    "hero.slide2.title": "تصميمات داخلية تنبض بالحياة",
    "hero.slide2.subtitle": "نحوّل رؤيتك إلى واقع ملموس",
    "hero.slide3.title": "خامات أوروبية بمعايير عالمية",
    "hero.slide3.subtitle": "جودة لا تقبل المساومة",
    "hero.slide4.title": "أكثر من 120 وحدة سكنية منفذة",
    "hero.slide4.subtitle": "خبرة 15 عاماً في التشطيبات الفاخرة",
    "hero.desc": "نصمم وننفذ تشطيبات وحدتك السكنية بتصاميم عصرية وجودة أوروبية — من الاستشارة الأولى إلى التسليم على المفتاح.",
    "hero.cta.quote": "اطلب عرض سعر مجاني",
    "hero.cta.work": "شاهد أعمالنا",

    "stat.years": "سنة خبرة",
    "stat.units": "وحدة سكنية",
    "stat.designs": "تصميم حصري",
    "stat.satisfaction": "رضا العملاء",

    "services.badge": "خدماتنا",
    "services.title": "خدمات تشطيب متكاملة",
    "services.desc": "نقدم باقة شاملة من خدمات تشطيب الوحدات السكنية الفاخرة بأجود الخامات وأمهر الحرفيين.",
    "service.structural": "التعديلات الإنشائية",
    "service.structural.desc": "هدم وإعادة بناء الجدران، تمديدات كهربائية مخفية، شبكات سباكة متطورة، تأسيس أنظمة تكييف مركزي.",
    "service.finishing": "التشطيبات المعمارية",
    "service.finishing.desc": "لياسة، دهانات ديكورية، ورق جدران. أرضيات راقية من باركيه، رخام، وبورسلين.",
    "service.gypsum": "أعمال الجبس والديكور",
    "service.gypsum.desc": "ألواح جبس بورد ديكورية، أسقف معلقة، توزيع إضاءة حديث، لد مخفي.",
    "service.carpentry": "النجارة والمطابخ",
    "service.carpentry.desc": "تصنيع مطابخ خشبية حسب المقاس، دواليب ملابس، وحدات تلفزيون، بانوهات ديكورية.",
    "service.handover": "التسليم النهائي",
    "service.handover.desc": "تنظيف شامل عميق، فحص نهائي، اختبار جميع الأنظمة، وتسليم المفتاح.",

    "showcase.badge": "أعمال مميزة",
    "showcase.title": "نماذج تشطيب وحدات سكنية فاخرة",
    "showcase.desc": "تصفح مشاريعنا المنفذة — كل مشروع يعكس التزامنا بالجودة والأناقة.",
    "showcase.living": "صالات معيشة فاخرة",
    "showcase.livingDesc": "تصاميم عصرية بأسقف مزخرفة وإضاءة مخفية",
    "showcase.bedroom": "غرف نوم راقية",
    "showcase.bedroomDesc": "خامات فاخرة ولمسات ديكورية مميزة",
    "showcase.kitchen": "مطابخ عصرية",
    "showcase.kitchenDesc": "تصنيع وتركيب مطابخ بأفضل الخامات",
    "showcase.bathroom": "حمامات فندقية",
    "showcase.bathroomDesc": "رخام طبيعي وأدوات صحية أوروبية",
    "showcase.sectionBadge": "ما نتقنه",
    "showcase.sectionTitle": "تشطيبات سكنية بمعايير فندقية",
    "showcase.sectionDesc": "كل ركن في منزلك يستحق عناية خاصة — من صالة المعيشة إلى أدق تفاصيل الحمام",

    "expertise.badge": "لماذا نحن",
    "expertise.title": "حرفية وتميز في التنفيذ",
    "expertise.desc": "أكثر من 15 عاماً من الخبرة في تحويل الوحدات السكنية إلى تحف في التشطيبات الفاخرة.",
    "expertise.whyTitle": "لماذا يثق بنا عملاؤنا في تشطيب منازلهم؟",
    "expertise.whyDesc": "نحن لا ننفذ تشطيباً عادياً — بل نصنع مساحة تعكس شخصيتك وذوقك الرفيع بأعلى معايير الاحترافية.",
    "expertise.card1": "ضمان جودة شامل",
    "expertise.card1Desc": "نلتزم بأعلى معايير الجودة مع ضمان على جميع الأعمال المنفذة.",
    "expertise.card2": "تصاميم عصرية ومبتكرة",
    "expertise.card2Desc": "تصاميم 3D قبل التنفيذ تساعدك على تخيل منزلك قبل البدء.",
    "expertise.card3": "التزام صارم بالمواعيد",
    "expertise.card3Desc": "جداول زمنية واضحة مع تحديثات دورية حتى التسليم.",
    "expertise.card4": "خامات أوروبية فاخرة",
    "expertise.card4Desc": "نتعامل مع أفضل موردي الخامات لضمان متانة وجمال التشطيبات.",

    "projects.badge": "مشاريعنا",
    "projects.title": "معرض أعمال متميز",
    "projects.desc": "تصفح مجموعتنا المتنوعة من الوحدات السكنية الفاخرة.",
    "projects.viewAll": "عرض جميع المشاريع",

    "timeline.badge": "رحلتنا",
    "timeline.title": "من الفكرة إلى الإنجاز",
    "timeline.desc": "عمليتنا المنظمة تضمن تجربة تشطيب سلسة.",
    "timeline.mainTitle": "من الفكرة إلى الاستلام في 5 خطوات",
    "timeline.step": "الخطوة",
    "timeline.s1": "استشارة وزيارة ميدانية",
    "timeline.s1Desc": "فريقنا يزور الشقة ويأخذ المقاسات بدقة ويناقش أفكارك.",
    "timeline.s2": "تصميم أولي (3D)",
    "timeline.s2Desc": "نقدم لك تصميماً ثلاثي الأبعاد للمساحات قبل بدء العمل.",
    "timeline.s3": "اعتماد العروض والمواد",
    "timeline.s3Desc": "نحدد الخامات النهائية والتكاليف بشفافية كاملة.",
    "timeline.s4": "التنفيذ والإشراف",
    "timeline.s4Desc": "نبدأ العمل تحت إشراف مهندسين متخصصين.",
    "timeline.s5": "التسليم النهائي",
    "timeline.s5Desc": "نسلمك منزل أحلامك جاهزاً للسكن.",

    "testimonials.badge": "آراء العملاء",
    "testimonials.title": "ماذا يقول عملاؤنا",
    "testimonials.desc": "تقييمات حقيقية من أصحاب منازل وثقوا بنا لتحقيق حلمهم.",
    "testimonials.sectionTitle": "آراء عملائنا",
    "testimonials.t1.name": "أحمد محمد",
    "testimonials.t1.location": "شقة - التجمع الخامس",
    "testimonials.t1.text": "فريق محترف ودقيق، التزموا بالجدول الزمني والجودة كانت أكثر من رائعة. أنصح بالتعامل معهم.",
    "testimonials.t2.name": "سارة عبدالله",
    "testimonials.t2.location": "فيلا - الشيخ زايد",
    "testimonials.t2.text": "من أفضل شركات التشطيبات التي تعاملت معها. الاهتمام بالتفاصيل والتصميم الداخلي كان مذهلاً.",
    "testimonials.t3.name": "محمد حسن",
    "testimonials.t3.location": "دوبلكس - الرحاب",
    "testimonials.t3.text": "تجربة ممتازة من البداية للنهاية. المهندسين متعاونين جداً والنتيجة النهائية فاقت توقعاتنا.",

    "cta.title": "مستعد لتحويل منزلك؟",
    "cta.desc": "احصل على استشارة مجانية وعرض سعر تفصيلي لمشروع تشطيب وحدتك السكنية.",
    "cta.button": "احصل على عرض سعر مجاني",
    "cta.call": "اتصل بنا الآن",

    "footer.about": "متخصصون في تشطيب وتصميم الوحدات السكنية الفاخرة بتصاميم عصرية وجودة أوروبية.",
    "footer.quickLinks": "روابط سريعة",
    "footer.services": "الخدمات",
    "footer.contact": "تواصل معنا",
    "footer.rights": "جميع الحقوق محفوظة",
    "footer.privacy": "سياسة الخصوصية",
    "footer.faq": "الأسئلة الشائعة",
    "footer.location": "القاهرة، مصر",
    "footer.legal": "المركز القانوني",
    "footer.channels": "القنوات الرسمية",
    "footer.sitemap": "خريطة الموقع",

    "about.heroTitle": "من نحن",
    "about.title": "عن لاكشري فينيشينج",
    "about.desc": "بدأنا رحلتنا في عالم التشطيبات الفاخرة منذ عام 2010، حاملين شعار الجودة والذوق الرفيع.",
    "about.story": "قصتنا",
    "about.storyText": "تحولنا من مجرد مقاولين إلى شركاء لأصحاب المنازل في تحقيق حلمهم. نؤمن بأن كل منزل يستحق لمسة فنية تعكس شخصية أصحابه.",
    "about.vision": "الرؤية",
    "about.visionText": "أن نكون الخيار الأول للتشطيبات السكنية الفاخرة في المنطقة.",
    "about.mission": "الرسالة",
    "about.missionText": "تقديم تجربة متكاملة تجمع بين التصميم المبتكر والتنفيذ المتقن.",
    "about.values": "قيمنا",
    "about.quality": "الجودة",
    "about.commitment": "الالتزام",
    "about.innovation": "الابتكار",
    "about.transparency": "الشفافية",
    "about.yearsExp": "سنة خبرة",
    "about.projectsDone": "مشروع منفذ",
    "about.repeatClients": "عميل مكرر",
    "about.team": "فريق القيادة",
    "about.ceo": "المدير التنفيذي",
    "about.projectMgr": "مدير المشاريع",
    "about.designMgr": "مديرة التصميم",

    "blog.heroTitle": "المدونة",
    "blog.title": "المدونة",
    "blog.desc": "أحدث اتجاهات الديكور والتشطيبات.",
    "blog.readMore": "اقرأ المزيد",
    "blog.post1": "أفكار ذكية لتصميم غرف المعيشة المفتوحة",
    "blog.post2": "دليلك لاختيار الأرضيات: باركيه أم رخام أم بورسلين؟",
    "blog.post3": "أحدث صيحات ألوان الدهانات الديكورية لعام 2024",
    "blog.post4": "كيف تختار تصميم المطبخ المثالي لمنزلك",
    "blog.post5": "أسرار الإضاءة الداخلية الاحترافية",
    "blog.post6": "دليل اختيار الخامات المناسبة للحمامات",
    "blog.cat.interior": "تصميم داخلي",
    "blog.cat.materials": "مواد بناء",
    "blog.cat.decor": "ديكور",
    "blog.excerpt1": "اكتشف أفضل الطرق لتصميم غرف معيشة مفتوحة تجمع بين الأناقة والوظيفية.",
    "blog.excerpt2": "مقارنة شاملة بين أنواع الأرضيات لمساعدتك في اتخاذ القرار الأمثل لمنزلك.",
    "blog.excerpt3": "تعرف على أحدث اتجاهات الألوان التي تضفي طابعاً عصرياً على مساحاتك.",
    "blog.excerpt4": "نصائح عملية لتصميم مطبخ يجمع بين الجمال والعملية.",
    "blog.excerpt5": "كيف تستخدم الإضاءة لتحويل أي مساحة إلى تحفة فنية.",
    "blog.excerpt6": "كل ما تحتاج معرفته عن خامات الحمامات الفاخرة.",
    "blogSection.title": "أحدث اتجاهات الديكور والتشطيبات",

    "contact.heroTitle": "اتصل بنا",
    "contact.title": "اتصل بنا",
    "contact.desc": "نسعد بتواصلك معنا لأي استفسار أو طلب.",
    "contact.phone": "الهاتف",
    "contact.email": "البريد الإلكتروني",
    "contact.address": "العنوان",
    "contact.addressValue": "الحي التجاري - القاهرة",
    "contact.sendMessage": "أرسل لنا رسالة",
    "contact.fullName": "الاسم الكامل",
    "contact.emailLabel": "البريد الإلكتروني",
    "contact.phoneLabel": "رقم الجوال",
    "contact.propertyType": "نوع العقار",
    "contact.selectProperty": "اختر نوع العقار",
    "contact.apartment": "شقة",
    "contact.villa": "فيلا",
    "contact.duplex": "دوبلكس",
    "contact.other": "أخرى",
    "contact.area": "مساحة العقار (م²)",
    "contact.message": "رسالتك",
    "contact.submit": "إرسال الرسالة",
    "contact.success": "تم إرسال رسالتك بنجاح!",
    "contact.successDesc": "سنتواصل معك في أقرب وقت ممكن.",
    "contact.workingHours": "ساعات العمل",
    "contact.satThu": "السبت - الخميس",
    "contact.friday": "الجمعة",
    "contact.closed": "مغلق",
    "contact.ourLocation": "موقعنا",

    "projectsPage.heroTitle": "معرض أعمالنا",
    "projectsPage.heroDesc": "استعرض مجموعة شاملة من مشاريعنا المنفذة في التشطيبات السكنية والتجارية بأعلى معايير الجودة والاحترافية.",
    "projectsPage.project": "مشروع",
    "projectsPage.photo": "صورة",
    "projectsPage.categories": "تصنيفات",
    "projectsPage.all": "الكل",
    "projectsPage.showProjects": "عرض المشاريع",
    "projectsPage.showGallery": "عرض الصور",
    "projectsPage.backToProjects": "العودة إلى المشاريع",
    "projectsPage.photos": "صورة",
    "projectsPage.showMore": "عرض المزيد",
    "projectsPage.remaining": "صورة متبقية",
    "projectsPage.showing": "عرض",
    "projectsPage.of": "من",
    "projectsPage.view": "عرض",

    "servicesPage.heroTitle": "خدماتنا",
    "servicesPage.heroDesc": "نقدم مجموعة متكاملة من خدمات التشطيب والتصميم الداخلي بأعلى معايير الجودة.",
    "servicesPage.extraTitle": "خدمات إضافية",
    "servicesPage.s1.title": "التعديلات الإنشائية والتأسيسات",
    "servicesPage.s1.desc": "هدم وإعادة بناء الجدران، تمديدات كهربائية مخفية، شبكات سباكة متطورة، تأسيس أنظمة تكييف مركزي وتبريد موزع.",
    "servicesPage.s2.title": "التشطيبات المعمارية الفاخرة",
    "servicesPage.s2.desc": "تنفيذ جميع أعمال التشطيبات بأعلى جودة من لياسة ودهانات ديكورية وورق جدران. تركيب أرضيات راقية من باركيه ورخام وسيراميك بورسلين.",
    "servicesPage.s3.title": "أعمال الجبس بورد والديكور",
    "servicesPage.s3.desc": "تصميم وتنفيذ أسقف جبس بورد معلقة متعددة المستويات، إفريزات، جدران ديكورية، إضاءة مخفية LED وكوفيات لإضفاء أجواء فاخرة.",
    "servicesPage.s4.title": "النجارة والمطابخ",
    "servicesPage.s4.desc": "تصميم وتصنيع وتركيب غرف نوم ومطابخ ووحدات تخزين وحلول ذكية باستخدام أفضل خامات الأخشاب والإكسسوارات.",
    "servicesPage.s5.title": "التشطيب والتسليم النهائي",
    "servicesPage.s5.desc": "تركيب جميع الأدوات الصحية والكهربائية الفاخرة، تجهيز المطابخ بالكامل، أعمال الزجاج والمرايا، والتسليم على المفتاح.",
    "servicesPage.extra1.title": "استشارات هندسية",
    "servicesPage.extra1.desc": "نقدم استشارات هندسية متخصصة لمساعدتك في اتخاذ القرارات الصحيحة.",
    "servicesPage.extra2.title": "إشراف على المشاريع",
    "servicesPage.extra2.desc": "إشراف هندسي متكامل لضمان تنفيذ أعلى معايير الجودة.",
    "servicesPage.extra3.title": "خدمات ما بعد البيع",
    "servicesPage.extra3.desc": "صيانة دورية وخدمات ما بعد التسليم لراحتك التامة.",

    "faq.heroTitle": "الأسئلة الشائعة",
    "faq.q1": "ما هي مدة تنفيذ مشروع التشطيب؟",
    "faq.a1": "تعتمد المدة على حجم المشروع ونوع التشطيبات المطلوبة. في المتوسط، تتراوح المدة بين 3 إلى 6 أشهر للشقق و6 إلى 12 شهراً للفلل.",
    "faq.q2": "هل تقدمون ضمان على الأعمال؟",
    "faq.a2": "نعم، نقدم ضمان شامل لمدة سنة على جميع أعمال التشطيب وسنتين على الأعمال الإنشائية.",
    "faq.q3": "كيف يتم تحديد التكلفة؟",
    "faq.a3": "يتم تحديد التكلفة بناءً على مساحة العقار، نوع التشطيبات، والخامات المختارة. نقدم عرض سعر تفصيلي وشفاف قبل البدء.",
    "faq.q4": "هل يمكنني اختيار الخامات بنفسي؟",
    "faq.a4": "بالطبع! نحن نساعدك في اختيار أفضل الخامات ونوفر لك خيارات متعددة تناسب ميزانيتك وذوقك.",
    "faq.q5": "هل تقدمون تصاميم 3D قبل التنفيذ؟",
    "faq.a5": "نعم، نقدم تصميمات ثلاثية الأبعاد لجميع المساحات حتى تتمكن من تصور النتيجة النهائية قبل البدء.",
    "faq.q6": "ما هي طرق الدفع المتاحة؟",
    "faq.a6": "نوفر خطط دفع مرنة تناسب ميزانيتك. يتم الدفع على مراحل مرتبطة بتقدم العمل.",
    "faq.q7": "هل تقدمون خدمات صيانة بعد التسليم؟",
    "faq.a7": "نعم، نقدم خدمات صيانة دورية وطوارئ بعد التسليم لضمان راحتك التامة.",
    "faq.q8": "هل يمكنني متابعة سير العمل؟",
    "faq.a8": "بالتأكيد! نوفر تحديثات دورية بالصور والفيديو ويمكنك زيارة الموقع في أي وقت.",

    "projectsSection.badge": "معرض الأعمال",
    "projectsSection.title": "أحدث مشاريعنا المنفذة",
    "projectsSection.desc": "اكتشف مجموعة مختارة من مشاريع التشطيبات السكنية والتجارية التي نفخر بتنفيذها",
    "projectsSection.viewAll": "عرض الكل",

    "quote.badge": "عرض سعر مجاني",
    "quote.title": "احصل على عرض سعر لمشروعك",
    "quote.desc": "أكمل النموذج التالي وسيتواصل معك فريقنا بعرض سعر تفصيلي خلال 24 ساعة",
    "quote.step1": "معلومات أساسية",
    "quote.step2": "تفاصيل العقار",
    "quote.step3": "الخدمات المطلوبة",
    "quote.step4": "الميزانية",
    "quote.step5": "المراجعة",
    "quote.name": "الاسم الكامل",
    "quote.phone": "رقم الهاتف",
    "quote.email": "البريد الإلكتروني (اختياري)",
    "quote.propertyType": "نوع العقار",
    "quote.area": "المساحة (م²)",
    "quote.floors": "عدد الطوابق",
    "quote.location": "الموقع",
    "quote.budget": "الميزانية التقديرية",
    "quote.notes": "ملاحظات إضافية",
    "quote.next": "التالي",
    "quote.prev": "السابق",
    "quote.submit": "إرسال الطلب",
    "quote.success.title": "تم إرسال طلبك بنجاح!",
    "quote.success.desc": "سيتواصل معك فريقنا خلال 24 ساعة لتقديم عرض السعر التفصيلي.",
    "quote.newRequest": "تقديم طلب جديد",
    "quote.selectServices": "اختر الخدمات التي تحتاجها (يمكنك اختيار أكثر من خدمة)",
    "quote.approxBudget": "الميزانية التقريبية",
    "quote.basicInfo": "معلوماتك الأساسية",
    "quote.propertyDetails": "تفاصيل العقار",
    "quote.selectedServices": "الخدمات المطلوبة",
    "quote.notesLabel": "ملاحظات",
    "quote.nameLabel": "الاسم",
    "quote.phoneLabel": "الهاتف",
    "quote.emailShort": "البريد",
    "quote.type": "النوع",
    "quote.areaLabel": "المساحة",
    "quote.locationLabel": "الموقع",
    "quote.floorsLabel": "الطوابق",
    "quote.budgetLabel": "الميزانية",
    "quote.error": "حدث خطأ",
    "quote.errorDesc": "لم نتمكن من إرسال الطلب. يرجى المحاولة مرة أخرى.",
    "quote.enterName": "أدخل اسمك الكامل",
    "quote.enterPhone": "01xxxxxxxxx",
    "quote.enterEmail": "example@email.com",
    "quote.enterArea": "مثال: 150",
    "quote.enterFloors": "مثال: 2",
    "quote.enterLocation": "مثال: التجمع الخامس، القاهرة الجديدة",
    "quote.enterNotes": "أي تفاصيل إضافية تود مشاركتها معنا...",
    "quote.service.structural": "التعديلات الإنشائية",
    "quote.service.finishing": "التشطيبات المعمارية",
    "quote.service.gypsum": "أعمال الجبس والديكور",
    "quote.service.carpentry": "النجارة والمطابخ",
    "quote.service.handover": "التسليم النهائي",
    "quote.service.consulting": "استشارات هندسية",
    "quote.budget1": "أقل من 100,000 جنيه",
    "quote.budget2": "100,000 - 300,000 جنيه",
    "quote.budget3": "300,000 - 500,000 جنيه",
    "quote.budget4": "500,000 - 1,000,000 جنيه",
    "quote.budget5": "أكثر من 1,000,000 جنيه",

    "chat.title": "مساعد لاكشري فينيشينج",
    "chat.subtitle": "الصيانة والاستفسارات والمرفقات والدعم الصوتي",
    "chat.placeholder": "اكتب رسالتك...",
    "chat.welcome": "مرحباً بك في لاكشري فينيشينج. يمكنني مساعدتك في الاستفسارات العامة، أو إنشاء طلب صيانة معمارية، أو الاستعلام عن طلب قائم.",
    "chat.newConversation": "محادثة جديدة",
    "chat.history": "المحادثات السابقة",
    "chat.download": "تنزيل نسخة من المحادثة",
    "chat.close": "إغلاق المحادثة",
    "chat.open": "فتح المحادثة",
    "chat.historyTitle": "سجل المحادثات",
    "chat.historyLead": "يمكنك الرجوع إلى أي محادثة سابقة أو حذفها أو بدء محادثة جديدة.",
    "chat.historyEmpty": "لا توجد محادثات محفوظة بعد",
    "chat.historyEmptyLead": "يبدأ السجل بالحفظ تلقائياً بعد أول رسالة من المستخدم.",
    "chat.historyCount": "محادثة محفوظة",
    "chat.current": "الحالية",
    "chat.clearAll": "مسح الكل",
    "chat.saved": "محفوظة",
    "chat.removeAttachment": "إزالة المرفق",
    "chat.attach": "إرفاق ملفات",
    "chat.record": "تسجيل صوتي",
    "chat.stopRecord": "إيقاف التسجيل",
    "chat.listen": "استمع",
    "chat.send": "إرسال",
    "chat.attachPlaceholder": "اكتب رسالتك أو أرفق ملفات...",
    "chat.downloadSuccess": "تم تنزيل نسخة من المحادثة الحالية.",
    "chat.clearSuccess": "تم مسح سجل المحادثات المحفوظة.",
    "chat.downloadEmpty": "لا توجد محادثة قابلة للتنزيل حالياً.",
    "chat.supportLead": "دعم المحادثة النصية والصوتية، إنشاء طلبات الصيانة، المرفقات، وسجل المحادثات السابقة.",
    "chat.attachmentsAssist": "مساعد متكامل للصيانة والاستفسارات والمرفقات",
    "chat.latestUpdate": "آخر تحديث",

    "theme.light": "نهاري",
    "theme.dark": "ليلي",

    "property.apartment": "شقة",
    "property.villa": "فيلا",
    "property.duplex": "دوبلكس",
    "property.penthouse": "بنتهاوس",
    "property.townhouse": "تاون هاوس",
    "property.studio": "استوديو",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("lf-lang");
    return (saved === "ar" || saved === "en") ? saved : "ar";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("lf-lang", newLang);
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang, dir]);

  const t = (key: string): string => {
    return translations[lang][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}
