location = /api/v1/auth/hooks {
  proxy_pass https://lnoyiwrulvoaaerpiqxc.supabase.co/functions/v1/auth-hooks;
  proxy_set_header Host lnoyiwrulvoaaerpiqxc.supabase.co;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location = /api/v2/whatsapp/hooks {
  proxy_pass https://lnoyiwrulvoaaerpiqxc.supabase.co/functions/v1/whatsapp-hooks;
  proxy_set_header Host lnoyiwrulvoaaerpiqxc.supabase.co;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location = /api/maintenance/gateway {
  proxy_pass https://lnoyiwrulvoaaerpiqxc.supabase.co/functions/v1/maintenance-gateway-api;
  proxy_set_header Host lnoyiwrulvoaaerpiqxc.supabase.co;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
